### ISSUE TITLE
Unecessary transaction output?

### ISSUE THREAD

**Issue by lannocc** [cyborg0922/bchpusher#1]
I could very well be mistaken, but I think this line (found twice in the code) creates an unecessary transaction output:

    rawtx = PrivateKey.create_transaction(
        [(PrivateKey.address, 0.0001, 'bch')], fee=1, message=pushdata, custom_pushdata=True)

Also I think it will fail if the user does not have 0.0001 BCH. In my usage of the BitCash library, I simply pass in an empty outputs array with my message and it automatically generates the 2 vouts.

**Comment by AustEcon** [comment]
Right you are! :) I had that on my to do list... was just a stop-gap measure to get it going.
An empty array! Of course! haha Thanks. Works great. :)
Sad day for the miners...
